// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS7S0vpn10DOj9xqngAfTPZzbt94jCQcA',
    appId: '1:684987115979:web:c54625cbbbeb7263466e4e',
    messagingSenderId: '684987115979',
    projectId: 'work-d0c57',
    authDomain: 'work-d0c57.firebaseapp.com',
    storageBucket: 'work-d0c57.firebasestorage.app',
    measurementId: 'G-FCW4YZJ7E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtQEa5U8sYb8POrAAGS9rSW73MC9tzCY',
    appId: '1:684987115979:android:cafeaba61b0a665c466e4e',
    messagingSenderId: '684987115979',
    projectId: 'work-d0c57',
    storageBucket: 'work-d0c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHnuAaeQemU-umvN-l8fNGi40bPS-0BBw',
    appId: '1:684987115979:ios:bf9996756cc9954e466e4e',
    messagingSenderId: '684987115979',
    projectId: 'work-d0c57',
    storageBucket: 'work-d0c57.firebasestorage.app',
    iosBundleId: 'com.example.workTogheter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHnuAaeQemU-umvN-l8fNGi40bPS-0BBw',
    appId: '1:684987115979:ios:bf9996756cc9954e466e4e',
    messagingSenderId: '684987115979',
    projectId: 'work-d0c57',
    storageBucket: 'work-d0c57.firebasestorage.app',
    iosBundleId: 'com.example.workTogheter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS7S0vpn10DOj9xqngAfTPZzbt94jCQcA',
    appId: '1:684987115979:web:7b2d7ef3d3c40ef9466e4e',
    messagingSenderId: '684987115979',
    projectId: 'work-d0c57',
    authDomain: 'work-d0c57.firebaseapp.com',
    storageBucket: 'work-d0c57.firebasestorage.app',
    measurementId: 'G-KJ0LTTJQ1P',
  );

}